
# OSIAM administration addon

FROM $REGISTRY/osiam-common:$OSIAM_VERSION

MAINTAINER tarent solutions GmbH <info@tarent.de>


# install OSIAM
ADD . /install 
RUN echo 'dbc_install=false' > /etc/dbconfig-common/osiam-${IMAGE}.conf \
    && DEBIAN_FRONTEND=noninteractive dpkg -i --ignore-depends=osiam-auth-server  --ignore-depends=osiam-resource-server /install/osiam-${IMAGE}_${OSIAM_VERSION}_all.deb \
    && rm -r /install

